# Site settings
title: Jesper Petersson
email: jp222wh@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  This site will be a front for my published assignments in a course called
  Client-based webbprogramming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Jesper Petersson
github_username:  Jeppepetersson

# Build settings
markdown: kramdown
