# Site settings
title: JP
email: jp222wh@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  This site will be a front for my published assignments in a course called
  Client-based webbprogramming.

  It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  Jeppepetersson

# Build settings
markdown: kramdown
